version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/example-javascript-yarn-2 # directory where steps will run
    docker: # run the steps with Docker
     # - image: timbru31/java-node 
      - image: loyaltyone/docker-alpine-java-node

      #- image: mongo:3.4.4 # and this image as the secondary service container      
 - checkout

      - run:
         name: install git
         command: apk add --no-cache git
        #arn
      
        name: install yarn
        command: yarn install --frozen-lockfile
      
      - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)
